name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: pull latest and remove old file from repo
        run: |
          git pull
          rm -f pack.zip
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'pack.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig /.idea/* *.iml'
      - name: push changes to remote
        run: |
          git add -A
          git commit -m "updated pack.zip"
          git push --force